import type { CoverageData } from '../components/CoverageTable'

export const COVERAGE_DATA: Record<string, CoverageData> = {
  adempiere: {
    titleEs: 'Cobertura funcional', titleEn: 'Functional Coverage',
    subtitleEs: 'Todo lo que incluye nuestra implementación de ADempiere ERP.',
    subtitleEn: 'Everything included in our ADempiere ERP implementation.',
    groups: [
      { labelEs: 'Gestión Financiera', labelEn: 'Financial Management', descEs: 'Control contable y de tesorería completo.', descEn: 'Complete accounting and treasury control.',
        itemsEs: ['Contabilidad General (GL)', 'Cuentas por Cobrar', 'Cuentas por Pagar', 'Gestión de Bancos y Caja', 'Presupuestos', 'Activos Fijos y Depreciación', 'Cierre de Período'],
        itemsEn: ['General Ledger (GL)', 'Accounts Receivable', 'Accounts Payable', 'Bank & Cash Management', 'Budgets', 'Fixed Assets & Depreciation', 'Period Closing'] },
      { labelEs: 'Gestión Comercial', labelEn: 'Commercial Management', descEs: 'Ciclo completo de compras, ventas y clientes.', descEn: 'Full purchase, sales and customer cycle.',
        itemsEs: ['Órdenes de Compra y Recepción', 'Órdenes de Venta y Facturación', 'Listas de Precios', 'CRM y Seguimiento de Prospectos', 'Gestión de Contratos', 'Comisiones de Ventas'],
        itemsEn: ['Purchase Orders & Receipts', 'Sales Orders & Invoicing', 'Price Lists', 'CRM & Lead Tracking', 'Contract Management', 'Sales Commissions'] },
      { labelEs: 'Operaciones y Logística', labelEn: 'Operations & Logistics', descEs: 'Inventario, almacenes y distribución.', descEn: 'Inventory, warehouses and distribution.',
        itemsEs: ['Inventario Multi-almacén', 'Órdenes de Transferencia', 'Gestión de Lotes y Series', 'Manufactura (BOM y Órdenes)', 'Distribución y Rutas'],
        itemsEn: ['Multi-warehouse Inventory', 'Transfer Orders', 'Lot & Serial Management', 'Manufacturing (BOM & Orders)', 'Distribution & Routes'] },
      { labelEs: 'Capital Humano', labelEn: 'Human Capital', descEs: 'Nómina, asistencia y gestión de personal.', descEn: 'Payroll, attendance and personnel.',
        itemsEs: ['Ficha de Empleado', 'Control de Asistencia', 'Nómina y Retenciones', 'Gestión de Préstamos', 'Vacaciones y Permisos'],
        itemsEn: ['Employee Record', 'Attendance Control', 'Payroll & Withholdings', 'Loan Management', 'Vacations & Permits'] },
      { labelEs: 'Plataforma', labelEn: 'Platform', descEs: 'Infraestructura y soporte técnico.', descEn: 'Infrastructure and technical support.',
        itemsEs: ['Despliegue Cloud o On-Premise', 'Multi-empresa y Multi-moneda', 'API REST / gRPC', 'Soporte y Mantenimiento', 'Capacitación de usuarios'],
        itemsEn: ['Cloud or On-Premise Deployment', 'Multi-company & Multi-currency', 'REST / gRPC API', 'Support & Maintenance', 'User Training'] },
    ],
  },
  odoo: {
    titleEs: 'Cobertura funcional', titleEn: 'Functional Coverage',
    subtitleEs: 'Módulos disponibles en nuestra implementación de Odoo.', subtitleEn: 'Modules available in our Odoo implementation.',
    groups: [
      { labelEs: 'Ventas y CRM', labelEn: 'Sales & CRM',
        itemsEs: ['CRM y Pipeline', 'Cotizaciones y Pedidos', 'Facturación electrónica', 'Suscripciones', 'Firma electrónica'],
        itemsEn: ['CRM & Pipeline', 'Quotes & Orders', 'E-invoicing', 'Subscriptions', 'E-signature'] },
      { labelEs: 'Finanzas', labelEn: 'Finance',
        itemsEs: ['Contabilidad General', 'Facturación y Pagos', 'Conciliación bancaria', 'Presupuestos', 'Reportes financieros'],
        itemsEn: ['General Accounting', 'Billing & Payments', 'Bank Reconciliation', 'Budgets', 'Financial Reports'] },
      { labelEs: 'Inventario y Compras', labelEn: 'Inventory & Purchasing',
        itemsEs: ['Inventario Multi-almacén', 'Órdenes de Compra', 'Recepción y Valoración', 'Reglas de reabastecimiento'],
        itemsEn: ['Multi-warehouse Inventory', 'Purchase Orders', 'Reception & Valuation', 'Replenishment Rules'] },
      { labelEs: 'Plataforma', labelEn: 'Platform',
        itemsEs: ['Cloud o Servidor propio', 'Multi-empresa', 'API REST', 'Soporte ERPyA'],
        itemsEn: ['Cloud or own server', 'Multi-company', 'REST API', 'ERPyA Support'] },
    ],
  },
  docker: {
    titleEs: 'Cobertura del servicio', titleEn: 'Service Coverage',
    subtitleEs: 'Todo lo que incluye nuestra gestión con Docker.', subtitleEn: 'Everything included in our Docker management.',
    groups: [
      { labelEs: 'Diseño y Arquitectura', labelEn: 'Design & Architecture',
        itemsEs: ['Análisis de requerimientos', 'Diseño de arquitectura', 'Ambientes dev/staging/prod', 'Selección de imágenes base'],
        itemsEn: ['Requirements analysis', 'Architecture design', 'Dev/staging/prod environments', 'Base image selection'] },
      { labelEs: 'Implementación', labelEn: 'Implementation',
        itemsEs: ['Dockerización de ERPs', 'Docker Compose multi-servicio', 'Redes y volúmenes', 'Variables de entorno'],
        itemsEn: ['ERP dockerization', 'Multi-service Docker Compose', 'Networks & volumes', 'Environment variables'] },
      { labelEs: 'CI/CD', labelEn: 'CI/CD',
        itemsEs: ['Pipeline de build', 'Tests de integración', 'Push a registro', 'Deploy automatizado'],
        itemsEn: ['Build pipeline', 'Integration tests', 'Push to registry', 'Automated deployment'] },
      { labelEs: 'Operación', labelEn: 'Operations',
        itemsEs: ['Logs centralizados', 'Métricas', 'Alertas', 'Backups', 'Soporte ERPyA'],
        itemsEn: ['Centralized logs', 'Metrics', 'Alerts', 'Backups', 'ERPyA Support'] },
    ],
  },
  kubernetes: {
    titleEs: 'Cobertura del servicio', titleEn: 'Service Coverage',
    subtitleEs: 'Capacidades incluidas en nuestra implementación de Kubernetes.', subtitleEn: 'Capabilities in our Kubernetes implementation.',
    groups: [
      { labelEs: 'Diseño del Clúster', labelEn: 'Cluster Design',
        itemsEs: ['Topología de nodos', 'Namespaces', 'Alta disponibilidad', 'Dimensionamiento'],
        itemsEn: ['Node topology', 'Namespaces', 'High availability', 'Resource sizing'] },
      { labelEs: 'Despliegue', labelEn: 'Deployment',
        itemsEs: ['Deployments y StatefulSets', 'ConfigMaps y Secrets', 'Ingress y Load Balancer', 'Helm Charts'],
        itemsEn: ['Deployments & StatefulSets', 'ConfigMaps & Secrets', 'Ingress & Load Balancer', 'Helm Charts'] },
      { labelEs: 'Escalabilidad', labelEn: 'Scalability',
        itemsEs: ['Horizontal Pod Autoscaler', 'Cluster Autoscaler', 'Rolling updates'],
        itemsEn: ['Horizontal Pod Autoscaler', 'Cluster Autoscaler', 'Rolling updates'] },
      { labelEs: 'Seguridad', labelEn: 'Security',
        itemsEs: ['RBAC', 'Network Policies', 'Prometheus/Grafana', 'Soporte ERPyA'],
        itemsEn: ['RBAC', 'Network Policies', 'Prometheus/Grafana', 'ERPyA Support'] },
    ],
  },
  'power-bi': {
    titleEs: 'Cobertura del servicio', titleEn: 'Service Coverage',
    subtitleEs: 'Todo lo que incluye nuestra implementación de Power BI.', subtitleEn: 'Everything in our Power BI implementation.',
    groups: [
      { labelEs: 'Conectividad', labelEn: 'Connectivity',
        itemsEs: ['ADempiere ERP (PostgreSQL)', 'Odoo ERP', 'Excel y Google Sheets', 'SQL/NoSQL', 'APIs REST'],
        itemsEn: ['ADempiere ERP (PostgreSQL)', 'Odoo ERP', 'Excel & Google Sheets', 'SQL/NoSQL', 'REST APIs'] },
      { labelEs: 'Reportes y Dashboards', labelEn: 'Reports & Dashboards',
        itemsEs: ['Dashboard financiero', 'Ventas y CRM', 'Inventario', 'KPIs de manufactura', 'RRHH'],
        itemsEn: ['Financial dashboard', 'Sales & CRM', 'Inventory', 'Manufacturing KPIs', 'HR'] },
      { labelEs: 'Distribución', labelEn: 'Distribution',
        itemsEs: ['Power BI Service', 'Reportes embebidos', 'Acceso por rol', 'App móvil'],
        itemsEn: ['Power BI Service', 'Embedded reports', 'Role-based access', 'Mobile app'] },
    ],
  },
  'apache-superset': {
    titleEs: 'Cobertura del servicio', titleEn: 'Service Coverage',
    subtitleEs: 'Todo lo que incluye nuestra implementación de Apache Superset.', subtitleEn: 'Everything in our Apache Superset implementation.',
    groups: [
      { labelEs: 'Infraestructura', labelEn: 'Infrastructure',
        itemsEs: ['Instalación en servidor o cloud', 'Docker/Kubernetes', 'PostgreSQL/MySQL', 'SSL y dominio'],
        itemsEn: ['Server or cloud install', 'Docker/Kubernetes', 'PostgreSQL/MySQL', 'SSL & domain'] },
      { labelEs: 'Visualizaciones', labelEn: 'Visualizations',
        itemsEs: ['Tablas dinámicas', 'Gráficos avanzados', 'Mapas', 'KPI cards', 'Drill-down'],
        itemsEn: ['Pivot tables', 'Advanced charts', 'Maps', 'KPI cards', 'Drill-down'] },
      { labelEs: 'Seguridad', labelEn: 'Security',
        itemsEs: ['LDAP/OAuth', 'Roles y permisos', 'Row-level security', 'Auditoría'],
        itemsEn: ['LDAP/OAuth', 'Roles & permissions', 'Row-level security', 'Auditing'] },
    ],
  },
  n8n: {
    titleEs: 'Cobertura del servicio', titleEn: 'Service Coverage',
    subtitleEs: 'Todo lo que incluye nuestra implementación de N8N.', subtitleEn: 'Everything in our N8N implementation.',
    groups: [
      { labelEs: 'Integración con ERP', labelEn: 'ERP Integration',
        itemsEs: ['Sincronización clientes/proveedores', 'Automatización de facturas', 'Alertas de inventario', 'Notificaciones de pedidos'],
        itemsEn: ['Customer/supplier sync', 'Invoice automation', 'Inventory alerts', 'Order notifications'] },
      { labelEs: 'Flujos de Negocio', labelEn: 'Business Flows',
        itemsEs: ['Aprobaciones automáticas', 'Email/Telegram/WhatsApp', 'Procesamiento PDF', 'Flujos condicionales'],
        itemsEn: ['Automatic approvals', 'Email/Telegram/WhatsApp', 'PDF processing', 'Conditional flows'] },
      { labelEs: 'Conectores', labelEn: 'Connectors',
        itemsEs: ['REST y Webhooks', 'Google Workspace', 'Microsoft 365', 'Bases de datos'],
        itemsEn: ['REST & Webhooks', 'Google Workspace', 'Microsoft 365', 'Databases'] },
    ],
  },
  pentaho: {
    titleEs: 'Cobertura del servicio', titleEn: 'Service Coverage',
    subtitleEs: 'Todo lo que incluye nuestra implementación de Pentaho.', subtitleEn: 'Everything in our Pentaho implementation.',
    groups: [
      { labelEs: 'ETL', labelEn: 'ETL',
        itemsEs: ['Conexión a ERP', 'Integración multi-fuente', 'Limpieza de datos', 'Transformaciones programadas'],
        itemsEn: ['ERP connection', 'Multi-source integration', 'Data cleaning', 'Scheduled transformations'] },
      { labelEs: 'Reportería', labelEn: 'Reporting',
        itemsEs: ['Reportes PDF/Excel', 'Reportes programados', 'Dinámicos por parámetro', 'Drill-down'],
        itemsEn: ['PDF/Excel reports', 'Scheduled reports', 'Parameterized reports', 'Drill-down'] },
      { labelEs: 'Dashboards', labelEn: 'Dashboards',
        itemsEs: ['Ejecutivo de ventas', 'Financiero', 'Inventario', 'KPIs en tiempo real'],
        itemsEn: ['Sales executive', 'Financial', 'Inventory', 'Real-time KPIs'] },
    ],
  },
  'ai-docs': {
    titleEs: 'Cobertura del servicio', titleEn: 'Service Coverage',
    subtitleEs: 'Todo lo que incluye la carga de documentos con IA.', subtitleEn: 'Everything in our AI document capture.',
    groups: [
      { labelEs: 'Captura', labelEn: 'Capture',
        itemsEs: ['OCR + IA generativa', 'PDF, JPG, PNG', 'Múltiples idiomas', 'Aprendizaje continuo'],
        itemsEn: ['OCR + generative AI', 'PDF, JPG, PNG', 'Multiple languages', 'Continuous learning'] },
      { labelEs: 'Documentos soportados', labelEn: 'Supported documents',
        itemsEs: ['Facturas de compra', 'Órdenes de compra', 'Notas de entrega', 'Recibos'],
        itemsEn: ['Purchase invoices', 'Purchase orders', 'Delivery notes', 'Receipts'] },
      { labelEs: 'Integración', labelEn: 'Integration',
        itemsEs: ['Detección automática de proveedor', 'Validación contra socio de negocio', 'Carga directa al ERP', 'Auditoría'],
        itemsEn: ['Automatic vendor detection', 'Business partner validation', 'Direct ERP loading', 'Auditing'] },
    ],
  },
  'ai-quotes': {
    titleEs: 'Cobertura del servicio', titleEn: 'Service Coverage',
    subtitleEs: 'Todo lo que incluye el análisis de cotizaciones con IA.', subtitleEn: 'Everything in our AI quote analysis.',
    groups: [
      { labelEs: 'Análisis', labelEn: 'Analysis',
        itemsEs: ['Comparación lado a lado', 'Análisis precio + plazo', 'Recomendación automática', 'Reglas configurables'],
        itemsEn: ['Side-by-side comparison', 'Price + lead-time analysis', 'Automatic recommendation', 'Configurable rules'] },
      { labelEs: 'Histórico', labelEn: 'History',
        itemsEs: ['Por proveedor', 'Alertas de variación', 'Tendencias de precio'],
        itemsEn: ['Per vendor', 'Variation alerts', 'Price trends'] },
      { labelEs: 'Integración', labelEn: 'Integration',
        itemsEs: ['Integración con OC', 'Carga masiva', 'Exportación a Excel'],
        itemsEn: ['PO integration', 'Bulk loading', 'Excel export'] },
    ],
  },
  seniat: {
    titleEs: 'Cobertura del servicio', titleEn: 'Service Coverage',
    subtitleEs: 'Todo lo que incluye la captura desde el portal del SENIAT.', subtitleEn: 'Everything in our SENIAT portal capture.',
    groups: [
      { labelEs: 'Consulta', labelEn: 'Query',
        itemsEs: ['Por número de RIF', 'Razón social y dirección fiscal', 'Estatus en tiempo real', 'Validación de contribuyente especial'],
        itemsEn: ['By RIF number', 'Legal name & tax address', 'Real-time status', 'Special-taxpayer validation'] },
      { labelEs: 'Automatización', labelEn: 'Automation',
        itemsEs: ['Creación automática de socio', 'Sin captcha manual', 'Auditoría de consultas', 'Cumplimiento fiscal'],
        itemsEn: ['Automatic partner creation', 'No manual captcha', 'Query audit', 'Tax compliance'] },
    ],
  },
  bcv: {
    titleEs: 'Cobertura del servicio', titleEn: 'Service Coverage',
    subtitleEs: 'Todo lo que incluye la carga de tasas BCV.', subtitleEn: 'Everything in our BCV rate loading.',
    groups: [
      { labelEs: 'Tasas', labelEn: 'Rates',
        itemsEs: ['USD, EUR y otras divisas', 'Tasa oficial diaria', 'Histórico completo', 'Aplicable a documentos'],
        itemsEn: ['USD, EUR & other currencies', 'Daily official rate', 'Full history', 'Applicable to documents'] },
      { labelEs: 'Automatización', labelEn: 'Automation',
        itemsEs: ['Carga programada automática', 'Sin intervención manual', 'Alertas de variación', 'Disponibilidad 24/7'],
        itemsEn: ['Scheduled automatic load', 'No manual intervention', 'Variation alerts', '24/7 availability'] },
    ],
  },
}
